version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: sudo pip install pytest
      - run:
          command: cd server && pytest --cov server test_utils.py --cov-report xml
          name: Test
      - run:
          command: bash <(curl -s https://codecov.io/bash)
          name: Upload

workflows:
  main:
    jobs:
      - build-and-test
