"""empty message

Revision ID: 04027fe73572
Revises: 
Create Date: 2020-04-05 14:11:24.505086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04027fe73572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('dest', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortlink_slug'), 'shortlink', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortlink_slug'), table_name='shortlink')
    op.drop_table('shortlink')
    # ### end Alembic commands ###
