"""Initial Setup

Revision ID: 0c874c460de2
Revises: 
Create Date: 2020-04-05 15:55:43.617477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c874c460de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('_slug', sa.String(), nullable=False),
    sa.Column('_dest', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortlink__slug'), 'shortlink', ['_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortlink__slug'), table_name='shortlink')
    op.drop_table('shortlink')
    # ### end Alembic commands ###
