"""empty message

Revision ID: 76272abf478a
Revises: 
Create Date: 2020-04-05 11:54:32.029674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76272abf478a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('dest', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortlink')
    # ### end Alembic commands ###
